// Auto-generated by generateClientHandlerTypes. Do not edit manually.

import type { HandlerModule, HandlerAssert } from "@mewhhaha/ruwuter/events";
import type * as Mod from "./add-passkey.client.mts";

type Fn = HandlerAssert<typeof Mod.default>;
declare const href: HandlerModule<Fn>;
export default href;
