#:schema node_modules/wrangler/config-schema.json
name = "zaraz2"
main = "./worker/main.ts"
build.watch_dir = "dist"
compatibility_flags = ["nodejs_als"]


compatibility_date = "2025-06-15"
assets = { directory = "./dist/", binding = "ASSETS" }


[[kv_namespaces]]
binding = "KV_USERS"
id = "d081ddb4cd634225bee59466c65f6c68"

[[durable_objects.bindings]]
name = "OBJECT_USER"
class_name = "DurableObjectUser"

[[durable_objects.bindings]]
name = "OBJECT_PASSKEY"
class_name = "DurableObjectPasskey"

[[durable_objects.bindings]]
name = "OBJECT_CHALLENGE"
class_name = "DurableObjectChallenge"

[observability.logs]
enabled = true

[vars]
ORIGIN = "https://zaraz2.app"


[[migrations]]
tag = "v1"
new_classes = [
    "DurableObjectUser",
    "DurableObjectPasskey",
    "DurableObjectChallenge",
]
