#:schema node_modules/wrangler/config-schema.json
name = "zaraz2"
main = "./worker/main.ts"
compatibility_flags = ["nodejs_als"]

compatibility_date = "2025-06-15"
assets = { binding = "ASSETS" }


[[durable_objects.bindings]]
name = "OBJECT_USER"
class_name = "DurableObjectUser"

[[durable_objects.bindings]]
name = "OBJECT_PASSKEY"
class_name = "DurableObjectPasskey"

[[durable_objects.bindings]]
name = "OBJECT_CHALLENGE"
class_name = "DurableObjectChallenge"

[observability.logs]
enabled = true

[vars]
ORIGIN = "https://zaraz2.app"

[[migrations]]
tag = "v1"
new_classes = [
    "DurableObjectUser",
    "DurableObjectPasskey",
    "DurableObjectChallenge",
]
